index: "hotdog"
dataset:
  path: "./data/nerf_synthetic/hotdog/"
geoms:
  points:
    select_k: 30
    init_num: 10000
training:
  add_start: 10000
  add_stop: 80000
  add_num: 500
eval:
  dataset:
    path: "./data/nerf_synthetic/hotdog/"
test:
  # load_path: "checkpoints/hotdog.pth"
  datasets:
    - name: "testset"
      path: "./data/nerf_synthetic/hotdog/"