index: "materials"
dataset:
  path: "./data/nerf_synthetic/materials/"
geoms:
  point_feats:
    dim: 128
training:
  add_start: 10000
  add_stop: 80000
  add_num: 500
eval:
  dataset:
    path: "./data/nerf_synthetic/materials/"
test:
  # load_path: "checkpoints/materials.pth"
  datasets:
    - name: "testset"
      path: "./data/nerf_synthetic/materials/"