index: "Barn"
dataset:
  coord_scale: 30.0
  type: "t2"
  path: "./data/tanks_temples/Barn/"
  factor: 2
  patches:
    height: 180
    width: 180
geoms:
  points:
    init_scale: [1.8, 1.8, 1.8]
    init_num: 5000
training:
  add_start: 10000
  add_stop: 35000
  lr:
    points:
      base_lr: 1.0e-2
eval:
  dataset:
    type: "t2"
    path: "./data/tanks_temples/Barn/"
    factor: 2
  img_idx: 0
test:
  # load_path: "checkpoints/Barn.pth"
  datasets:
    - name: "testset"
      type: "t2"
      path: "./data/tanks_temples/Barn/"
      factor: 2