index: "Caterpillar"
use_amp: false
dataset:
  coord_scale: 30.0
  type: "t2"
  path: "./data/tanks_temples/Caterpillar/"
  factor: 2
  patches:
    height: 180
    width: 180
geoms:
  points:
    init_scale: [1.0, 1.0, 1.0]
    init_num: 5000
  background:
    constant: 4.0
models:
  attn:
    embed:
      k_L: [4, 4, 4]
      q_L: [4]
      v_L: [4, 4]
training:
  add_start: 10000
  add_stop: 80000
  add_num: 500
  lr:
    points:
      base_lr: 6.0e-3
eval:
  dataset:
    type: "t2"
    path: "./data/tanks_temples/Caterpillar/"
    factor: 2
  img_idx: 0
test:
  # load_path: "checkpoints/Caterpillar.pth"
  datasets:
    - name: "testset"
      type: "t2"
      path: "./data/tanks_temples/Caterpillar/"
      factor: 2