index: "body_01"
dataset:
  type: "humbi"
  path: "./data/humbi/body_01"
geoms:
  points:
    init_num: 10000
training:
  add_start: 10000
  add_stop: 50000
eval:
  dataset:
    type: "humbi"
    path: "./data/humbi/body_01"
  img_idx: 0
test:
  # load_path: "checkpoints/chair.pth"
  datasets:
    - name: "testset"
      type: "humbi"
      path: "./data/humbi/body_01"
